import type { Metadata } from "next";
import {  Work_Sans, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  className={`${workSans.variable} ${inter.variable}`} lang="en">
      <body
        className={` antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
